name: 'Publish NPM Package'

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish NPM Package
    runs-on: ubuntu-latest
    environment: npm
    timeout-minutes: 5

    steps:
      - name: Checkout 🛎
        id: checkout
        uses: actions/checkout@master

      - name: Setup node env 🏗
        id: setup
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Get yarn cache directory path 🔃
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules 📦
        uses: actions/cache@v3.0.7
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies 👨🏻‍💻
        id: install
        run: yarn install --frozen-lockfile

      - name: Publish to npm 📩
        id: npm-publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false
          check-version: false
